### PR TITLE
Append name of part to title

### PR DESCRIPTION
**Pull request by nielserik**
UC has asked if name-of-part (245$p) could be appended to the title since $p is sometimes the only distinguishing element of multiple titles that are otherwise identical. 

I suppose extending the title like that would be fine with other institutions; do you have an opinion about that @maccabeelevine ?

### CODE REVIEW

**Comment by maccabeelevine** [comment]
No opinion here, I don't know the MARC well enough.  I will ask the folks here who use it...

**Comment by nielserik** [comment]
> No opinion here, I don't know the MARC well enough. I will ask the folks here who use it...

No problem @maccabeelevine. I'm pretty sure it will be fine but let's see if you hear something else and I can move it to the "chi" mapping. 

We have a few more UC mapping request coming, if you want to ask about them too while you're at it:

-  Map Instance resource type from 336, like "text":  
     =336  \\$atext$btxt$2rdacontent$0http://id.loc.gov/vocabulary/contentTypes/txt
-  Map Instance format from 337 "--" 338, like "unmediated -- volume":
     =337  \\$aunmediated$bn$2rdamedia$0http://id.loc.gov/vocabulary/mediaTypes/n
     =338  \\$avolume$bnc$2rdacarrier$0http://id.loc.gov/vocabulary/carriers/nc

**Comment by maccabeelevine** [comment]
Lisa agrees: "245$p is valid and should be accepted by the validation part of the tool - yes"

**Comment by lmccoll44** [comment]
The items on the list with bullet points are all fine - yes - generic enough. We do not use copy numbers at Lehigh so we would not want that field to populate on import. Thank you for checking!

**Pull request merged**
